on:
  push

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}
            
      - name: Compile Icons
        uses: AAGaming00/sass-build@master
        with:
          source: style-icons.scss
          destination: style-icons.css
      
      - name: Add and Commit changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add ./style-icons.css
          git diff-index --quiet HEAD || git commit -m 'Updated compiled CSS files'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}